services:
  api:
    container_name: order-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "${API_PORT:-8010}:${API_PORT:-8010}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${APIP_PORT:-8010}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT:-8010}/health || exit 1" ]   # It will be updaate
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped